# write programs in python using numpy library to do 


a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis


In [2]:
import numpy as np

arr=np.array(np.random.randint(0,100,(4,4)))
print(arr)

[[52  1 51 43]
 [44  8  8 76]
 [72 82 83 80]
 [35 68 40 58]]


In [11]:
mean=np.mean(arr,axis=1)
print("MEAN is :",mean)

MEAN is : [33.   60.25 60.   38.  ]


In [12]:
sd=np.std(arr,axis=1)
print("Standard Deviation is :",sd)

Standard Deviation is : [29.76575213 10.87140745 14.54303957 29.42787794]


In [15]:
var=np.var(arr,axis=1)
print("Variance is:",var)

Variance is: [886.     118.1875 211.5    866.    ]


b. Get the indices of the sorted elements of a given array
    B=[56,48,22,41,78,91,24,46,8,33]

In [3]:
B=np.array([56,48,22,41,78,91,24,46,8,33])
print(B)
print('Indices of sorted element of array B :',np.argsort(B))

[56 48 22 41 78 91 24 46  8 33]
Indices of sorted element of array B : [8 2 6 9 3 7 1 0 4 5]


c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data 
    type of the array and then reshape it into n x m array, n and m are user inputs given at the run time.

In [38]:
m=int(input("Enter the rows: "))
n=int(input("Enter the columns :"))
arr=np.array(np.random.randint(0,10,(m,n)))
print("The array is :\n",arr)
print('The shape of the array is :',arr.shape)
print('The type of array is :',arr.dtype)
print('The data type is :',type(arr))
print("The reshaped array is :\n",arr.reshape(n,m))

Enter the rows: 4
Enter the columns :3
The array is :
 [[5 9 6]
 [7 7 1]
 [8 9 2]
 [8 1 0]]
The shape of the array is : (4, 3)
The type of array is : int32
The data type is : <class 'numpy.ndarray'>
The reshaped array is :
 [[5 9 6 7]
 [7 1 8 9]
 [2 8 1 0]]


d. Test whether the elements of a given array are zero, non-zero, and NaN .Record the indices of these elements in three separate arrays.

In [44]:
Arr=np.array([0,10,-1,np.nan,0,23,-np.nan,4])
print(Arr)
nan=[]
zero=[]
nonZero=[]
for  i,ele in enumerate(Arr):
    if(np.isnan(ele)):
        nan.append(i)
    elif(ele!=0):
        nonZero.append(i)
    else:
        zero.append(i)
print("testing array for NaN:",nan)
print('testing array for zero :',zero)
print('testing array for non zero :',nonZero)

[ 0. 10. -1. nan  0. 23. nan  4.]
testing array for NaN: [3, 6]
testing array for zero : [0, 4]
testing array for non zero : [1, 2, 5, 7]
